apiVersion: apps/v1
kind: Deployment
metadata:
  name: hausmeister-scheduler-deployment
  labels:
    app: hausmeister-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hausmeister-scheduler
  template:
    metadata:
      labels:
        app: hausmeister-scheduler
    spec:
      containers:
        - name: hausmeister-scheduler
          image: madhavontheweb/hausmeister-scheduler:latest
          imagePullPolicy: "Always"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5050"
            - name: APP_NAME
              value: hausmeister-scheduler
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: heykaavi-secret
                  key: mongo-dev-url
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: hausmeister-scheduler-service
spec:
  ports:
    - port: 80
      targetPort: 5050
  selector:
    app: hausmeister-scheduler
